apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: uiptel
  labels:
    app: api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ${DIGEST}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: production
          - name: APP_SECRET
            value: some-app-secret-13131987498727
          - name: DB_URL
            value: mysql://uiptel:pa$$$$4uIPtel@mysql.default/uiptel
          - name: DIGEST_IMAGE
            value: ${DIGEST}
        ports:
          - containerPort: 3000
