apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: uiptel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  tls:
  - hosts:
      - uiptel.com
    secretName: uiptel-tls-cert
  rules:
  - host: uiptel.com
    http:
      paths:
      - path: /api(/|$)(.*)
        backend:
          serviceName: api
          servicePort: 3000
