version:  '3.7'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass4r00t
      MYSQL_DATABASE: uiptel
      MYSQL_USER: uiptel
      MYSQL_PASSWORD: pass4uiptel
    volumes:
      - ./.db_data:/var/lib/mysql

  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80

  api:
    depends_on:
      - db
    container_name: ${CONTAINER_NAME}
    image: anryzhov/node-dev:buster-slim
    command: ["sleep.js"]
    environment:
      DB_URL: 'mysql://uiptel:pass4uiptel@db/uiptel'
      NODE_ENV: development

    hostname: '${APP_NAME}'
    working_dir: ${APP_PATH}
    volumes:
      - /home/${USER_NAME}:/home/${USER_NAME}
      - ./:${APP_PATH}
    ports:
      - 3000:3000

networks:
  default:
    driver: bridge
    name: ${NAMESPACE}
