name: deploy

on:
  push:
    branches: master

jobs:
  image-deploy:
    env:
      KUBEHOME: ${{ github.workspace }}/.kube
      KUBECONFIG: ${{ github.workspace }}/.kube/config

    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v2

      - name: Deploy Kube config
        run: |
          mkdir -p ${KUBEHOME} \
            && echo ${{ secrets.KUBECONFIG }} | base64 -d > ${KUBECONFIG}
      
      - name: Check kubectl version 
        run: |
            kubectl version \
            && kubectl get po
