name: test
on:
  push:
    branches: master
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          username: anryzhov
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build
